travis:
  secure:
    BINSTAR_TOKEN: 4Cjb4SADYPQwe29FdnsGgeubokGDulIlnhaqgilPSaPS3nmgKWOGyak/gPeB3fe6Na7vi2mzp48rr1nBhYfH9bQ/FhkHPQPUoZScvKzzRoAVeju3HPIbDJ12s5tcDpjB1D5P4A8QLnqfW1+UXiIkhvHvRwPA8CT/OK/VTgAuOtCHGbbLe7OgQjwGarxR8KJZu73aMin420DxiT1HbB0jIzdwd/otSLpvHRAnjOXdtE7tl9Dgu2uI8IaNecpOfXgJDK+V2PG0C9eK1sclqEvYhD6/vg2qWz5HU1U1mty0STOk5A5dAGsZgklKlrY+/P5wMXgTsbVSrqZp/ogFjjad/2e33vN1KDqRqdzh+sweOLi2peKdO47PdTuYabE8gV2KGgY011t9YsLkyIaHkmU+IkXc9q6xPHQDaa5MuzCpH4jNUoEeFIfkp4f+b9/ESv1BUaYWRrB5ckaUMI9FjDuwMLerDxr6qlWax0SdBNDTaEOqEdt8bVz8TmRdgk9f1TkFKSsQr4zvGK8/cMrKJscytlnz6+bppgmkrW4v47Ls3j+/UaV0PEaQ7JSzdp+8U9WKV79kszb4b2EpfNuOIRPIXQwDF6ikmVfyH6s+uEduxZmxzDscKL2bi03EeAUJ113p/5vSslKIYwXogjDvtkwd6Dx2CJQxAi8YaIg/XluhMuw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
