travis:
  secure:
    BINSTAR_TOKEN: XTePAWXK9FlKfWKZcgzvTnohxbSpyGTgZN/bBIL6K9RLQCbrClefJ8X46RSj6mSnwdAFWBA74/PdJzdeJzXDLbSzL6elkTPJ5TP4ORQHlO4RF9r8OxORh+2jQ7UZ8NSySzE4/L3CLkpHs6MK160XCW5uCWPk7zMBaIXnoxSew+/oh53YW5eiqyE8Vnd+xPTVDX/U50PlIKpV/oZl8OkaQ4rLqPaZoXLnXgg1r0n72PmLTymH6x51IdtFwy0vvkDTKWX42eB78m2bkckjek7y8pIUQuDbna8kC8HA4fzFwBPKNAUOXRxi2sFH+lV2Fqqsr1k5xS8R1R+MItGRIBfJ6kOA5M4PrBC/UL/y3w5Iwqw8ojUWGt/R35Cxjao28hFk+s3KfJinwR7+QcFD9ERUvG+MdiyekxkXTRtl8a02sKzHdmDM2vPbZ+PPIDkVhcS8rRkJBe7AzCEb5FUUzMcpF3oj+i/zeqLTV7o6+ZXydI6dwF1R7SWN68Ogml1hfFVcYxMPetlICMXt3sv2GW0KzfLS35/NxcV1g+iv4mCuuTGu2cO/0WfSrE6dzCW6Mz1QfvCOvDYadu6bXxFspjLW5lu3Onq7NM6ZEkP+/9I28s5XDZCm9BGnf28FwMuvJmssGzmO1sn1WJeQQtKTn8Onr7Bxeilaa3dusEvLif5/Ufk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
